---
- name: install and restart the httpd
  hosts: all
  become: true
  tasks:
    - name: install https
      package:
        name: httpd
        state: latest

    - name: copy the war file
      copy:
        src: /var/lib/jenkins/workspace/ansible-httpd/target/ansible-httpd.war
        dest: /var/www/html
        
    - name: copy index file
      copy:
        src: /var/lib/jenkins/workspace/ansible-httpd/src/main/webapp/index.jsp
        dest: /var/www/html

    - name: restart the service
      service:
        name: httpd
        state: started


